version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: saturday
    groups:
      go-dependencies:
        update-types:
          - minor
          - patch
    labels:
      - dependencies

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: saturday
    groups:
      docker-images:
        update-types:
          - minor
          - patch
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
    groups:
      github-actions:
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - area:ci
