version: "2"
run:
  go: "1.26"
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - revive
    - rowserrcheck
    - staticcheck
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: _test\.go
formatters:
  enable:
    - gofmt
    - goimports
